config/routes.rb
Rails.application.routes.draw do

    root 'welcome#index'
    get 'products' => 'products#list', as: :products
    get 'products/detail/:id' =>  'products#detail', as: :detail

end

app/models/product.rb
class Product
    attr_accessor :pid, :item, :description, :price, :condition, :dimension_w, :dimension_l, :dimension_h, :img_file, :quantity, :category
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
require 'csv'

class ProductsController < ApplicationController

  def list
    @products = fetch_products
  end

  def detail
   @products = fetch_products

    @product = @products.find {|p| p.pid == params[:id]}
  end

  def discount_price
    case @product.condition
    when @product.condition == "good"
      "#{ @price *0.9 } ITEM ON CLEARANCE! 10% off!"
    when @prodcut.condition == "average"
      "#{ @price *0.8 } ITEM ON CLEARANCE! 20% off!"
    else
      @price
    end
  end



    def fetch_products
      products = []

      CSV.foreach("#{Rails.root}/mf_inventory.csv", headers: true) do |row|
        product_hash = row.to_hash

          if product_hash["quantity"].to_i > 0

          product = Product.new
          product.pid = product_hash['pid']
          product.item = product_hash['item']
          product.description = product_hash['description']
          product.price = product_hash['price']
          product.condition = product_hash['condition']
          product.dimension_w = product_hash['dimension_w']
          product.dimension_l = product_hash['dimension_l']
          product.dimension_h = product_hash['dimension_h']
          product.img_file = product_hash['img_file']
          product.quantity = product_hash['quantity']
          product.category = product_hash['category']

          products << product
         end
      end
      products
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MalloryFurniture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="home-back">
    <ul>
      <li>
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
          <% end %>
        </a>
      </li>
      <li>
        <%= link_to :back do %>
          <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
         <% end %>
      </li>
    </ul>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/products/detail.html.erb
<div class="page-header">
  <h1><%= @product.item %></h1>
</div>

<div class="row">
  <div class="col-xs-8">
    <div class="thumbnail text-center">
      <%= image_tag @product.img_file, class: "large" %>
    </div>
  </div>

  <div class="col-xs-4">

    <div class="well">

        <ul class="list-group">
          <li class="list-group-item"><strong>Price: </strong>

          <% if @product.condition == "good" %> <br><span class="badge">CLEARANCE: 10% OFF!</span>
          <%= number_to_currency @product.price.to_i * 0.9 %>
          <% elsif @product.condition == "average" %> <br><span class="badge">CLEARANCE: 20% OFF</span>
          <%= number_to_currency @product.price.to_i * 0.8 %>
          <% else %>
          <%= number_to_currency @product.price %>
          <% end %>

        </li>
          <li class="list-group-item"><strong>Description: </strong><br><%= @product.description %></li>
          <li class="list-group-item">
            <strong>Dimensions:</strong><br>Width:
            <%= @product.dimension_w%><br>Length
            <%= @product.dimension_l%><br>Height:
            <%= @product.dimension_h%><br>
          </li>
          <%= link_to 'Back to Items', products_path, class: "btn btn-lg btn-block btn-warning" %>
        </ul>

      </div>

  </div>
</div>

app/views/products/list.html.erb
<div class="page-header">
  <h1>Mallory Furniture</h1>
</div>


<% @products.in_groups_of(3, false) do |products| %>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-xs-4">
        <div class="thumbnail">

          <%= image_tag product.img_file, class: "small" %>

          <div class="caption">
            <h3><%= product.item %></h3>
            <p><%= number_to_currency product.price %></p>
            <%= link_to 'More Info', detail_path(id: product.pid), class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Mallory Furniture</h1>
</div>


<div class="jumbo">
  <div class="littlebox">
    <p>Not Too Shabby....</p>
    <p>
      <%= link_to 'Check Out Our Products', products_path, :class => "btn btn-primary btn-lg" %>
    </p>
  </div>
</div>